name: Shadowsocks Server

on:
  workflow_dispatch: # Manuel tetikleme

jobs:
  setup-shadowsocks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Shadowsocks
      run: |
        sudo apt-get update
        sudo apt-get install -y shadowsocks-libev
        sudo bash -c 'cat > /etc/shadowsocks-libev/config.json <<EOF
        {
          "server":"0.0.0.0",
          "server_port":8388,
          "password":"${{ secrets.SHADOWSOCKS_PASSWORD }}",
          "timeout":300,
          "method":"chacha20-ietf-poly1305",
          "fast_open":true,
          "nameserver":"8.8.8.8"
        }
        EOF'
        sudo systemctl enable shadowsocks-libev
        sudo systemctl start shadowsocks-libev

    - name: Get Server IP
      run: |
        echo "Shadowsocks sunucusu aktif! IP: $(curl -s ifconfig.me)"
        echo "Port: 8388, Şifre: ${{ secrets.SHADOWSOCKS_PASSWORD }}, Şifreleme: chacha20-ietf-poly1305"

    - name: Keep Server Running
      run: |
        sudo tail -f /var/log/syslog
